if (Meteor.isClient) {
  Template.demo.helpers({
    counter: function() {
      return Posts.find({}).count();
    },
    posts: function() {
      return Posts.find({});
    }
  });

  Template.demo.events({
    'click button': function () {
      // add a demo post
      Posts.insert({
        'url': 'http://www.google.com',
        'title': 'lorem ipsum...',
        'summary': 'this would be an autogenerated summary of the post content'
      });
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
  });
}
