Template.postsList.onCreated(function() {
  this.subscribe('posts');
});

Template.postsList.helpers({
  counter: function() {
    return Posts.find({}).count();
  },
  posts: function() {
    return Posts.find({});
  }
});

Template.postsList.events({
  'click button': function () {
    // add a demo post
    Posts.insert({
      'url': 'http://www.google.com',
      'title': 'lorem ipsum...',
      'summary': 'this would be an autogenerated summary of the post content'
    });
  }
});
