Template.submitNewPost.onCreated(function() {
  // Redirect if not logged in
  this.autorun(function() {
    if (!Meteor.userId()) {
      FlowRouter.go('/');
    }
  });
});

Template.submitNewPost.events({
  'submit form': function (e) {
    e.preventDefault();
    // add a demo post
    var postId = Posts.insert({
      'url': $(e.target).find('#url').val(),
      'title': $(e.target).find('#title').val(),
      'summary': 'this would be an autogenerated summary of the post content'
    });
    FlowRouter.go('postPage', { id: postId });
  }
});
