Template.submitNewPost.onCreated(function() {
  // Redirect if not logged in
  this.autorun(function() {
    if (!Meteor.userId()) {
      FlowRouter.go('/');
    }
  });
});

Template.submitNewPost.events({
  'click button': function () {
    // add a demo post
    Posts.insert({
      'url': 'http://www.google.com',
      'title': 'lorem ipsum...',
      'summary': 'this would be an autogenerated summary of the post content'
    });
  }
});
